version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=246800#
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
  db:
    driver: local

  redisdata:
    driver: local
